### PR TITLE
Fix list_join for user data scripts

### PR DESCRIPTION
**Pull request by bogdando**
Signed-off-by: Bogdan Dobrelya <bogdando@mail.ru>

### CODE REVIEW

**Comment by bogdando** [comment]
@sathlan PTAL, tested this locally

**Comment by bogdando** [comment]
I need to double-check :)

**Comment by bogdando** [comment]
@sathlan @slagle folks, PTAL the fix. W/o it, user data scripts merge with a 'n' symbol injected, which breaks cloud-init execution. I tested it locally, worked for me...

**Review by holser — APPROVED** [review]
Before patch /var/log/cloud-init-output.log shows
+ '[' -n '' ']'
+ nrpm -q git

After patch git is installed correctly

**Comment by bogdando** [comment]
@slagle PTAL

**Comment by sathlan** [comment]
I end up using "\n" which work as well.  Testing with ''.

**Pull request merged**
